services:
  # Servicio de inferencia
  inference-service:
    build:
      context: .
      dockerfile: DockerfileInferenceCPU
    image: flowguard-stgnn-inference-cpu:v1
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      AWS_ACCESS_KEY_ID: "X"
      AWS_SECRET_ACCESS_KEY: "X"
      AWS_DEFAULT_REGION: "X"
      MODEL: "cognn"
      CLIENT: "ESAMUR"
      ROOT: "http://172.25.0.2:9090"
      TASK: "inference"
    command: >
      --device 'cpu'
      --scaling_required False
      --scaler_path 'scale_params.csv'
      --model_path 'local'
      --N 12
      --Nulo 0
      --Metodo MEDIANA10
    restart: unless-stopped
    networks:
      iot_network:
        ipv4_address: 172.25.0.4
    user: "0:0"


networks:
  iot_network:
    external: true                       # Esto le dice a Docker que la red ya existe
    name: flowguard-compose_iot_network  # Usa el nombre de la red que ya existe
