import numpy as np
from sklearn.metrics import precision_score, recall_score, roc_auc_score, f1_score, average_precision_score, confusion_matrix
from tqdm import tqdm
from multiprocessing import Pool
import wandb
import os

## EVALUATING FUNCTION
def pointwise_evaluation(gt_labels, pred_labels, scoring):
    """
        Evaluates the model's predictions against ground truth labels.

        Parameters:
        -----------
        gt_labels : array-like
            Ground truth binary labels (0 or 1).
        pred_labels : array-like
            Predicted binary labels (0 or 1).
        scoring : array-like
            Continuous scores from the model to determine thresholds.

        Returns:
        --------
        dict
            A dictionary containing various evaluation metrics, including
            auto precision, auto recall, auto F1 score, ROC AUC, PRC AUC,
            best precision, best recall, and best F1 score.
    """
    ## non-iterative
    auto_recall = recall_score(gt_labels, pred_labels)
    auto_precision = precision_score(gt_labels, pred_labels)
    auto_f1 = f1_score(gt_labels, pred_labels)
    roc = roc_auc_score(gt_labels, scoring)
    prc = average_precision_score(gt_labels, scoring)

    scoring = np.array(scoring)
    sorted_scoring = np.sort(np.array(scoring))

    best_recall, best_precision, best_f1 = 0, 0, 0
    ## iteratively to get best f1 result
    pointwise_f1_evaluator = pointwise_best_f1(gt_labels,scoring)
    f1s = pointwise_f1_evaluator.go()

    best_index = f1s.index(max(f1s))
    best_thres = sorted_scoring[best_index]
    best_pred = scoring > best_thres
    # Best results
    best_f1 = f1_score(gt_labels,best_pred)
    best_recall = recall_score(gt_labels,best_pred)
    best_precision = precision_score(gt_labels,best_pred)
    cm = confusion_matrix(gt_labels, best_pred)
    best_tn, best_fp, best_fn, best_tp = cm.ravel()
    best_fpr = best_fp / (best_fp + best_tn)
    best_fnr = best_fn / (best_fn + best_tp)
    
    if os.environ["WANDB_RUN"]=="true":
        wandb.log({"F1 score": best_f1,
                   "precision": best_precision,
                   "recall": best_recall,
                   "Precision": best_precision,
                   "Recall": best_recall,
                   "False +": best_fpr,
                   "False -": best_fnr,
                   "ROC-AUC": roc,
                   "PRC-AUC": prc,
                   "threshold": best_thres
                   })
    # Save values of metrics to metadata
    os.environ['threshold_best'] = str(best_thres)
    # Saves
    if os.environ["TASK"] != "re-train":
        np.save(f"/app/save/{os.environ['CLIENT']}/{os.environ['sweep_proyect']}/{os.environ['run_name']}/gt_labels_0.npy", gt_labels)
        np.save(f"/app/save/{os.environ['CLIENT']}/{os.environ['sweep_proyect']}/{os.environ['run_name']}/scoring_0.npy", scoring)

    output = dict(auto_precision=auto_precision,auto_recall=auto_recall,auto_f1=auto_f1,
                  roc=roc,prc=prc,best_precision=best_precision,
                  best_recall=best_recall,best_f1=best_f1)
    return output


def early_detection_evaluation(truth, scoring, delay=[0,6,30,60,120,180,360]):
    """
        Evaluates early detection performance at specified time delays.

        Parameters:
        -----------
        truth : array-like
            Ground truth binary labels (0 or 1) for the events of interest.
        scoring : array-like
            Continuous scores produced by the model used to determine detection.
        delay : list of int, optional
            Time delays (in seconds) at which to evaluate the early detection.
            Default values are [0, 6, 30, 60, 120, 180, 360].

        Returns:
        --------
        dict
            A dictionary containing the best F1 score for each specified delay.
    """
    assert len(truth) == len(scoring)

    output = {}

    for d in delay:
        early_evaluator = early_best_f1(truth,scoring,d)
        early_results = early_evaluator.go()
        best_score = max(early_results)
        output["delay_"+str(d)] = best_score

    return output

class pointwise_best_f1():
    """
        Evaluator to calculate pointwise F1 score based on different scoring thresholds.

        This class allows for the evaluation of a model's performance by calculating the F1 score for different
        prediction thresholds. The best F1 score can be determined from the ground truth labels and the predicted
        scores generated by the model.

        Attributes:
        -----------
        gt_labels : array-like
            Ground truth labels (0 or 1) indicating the presence or absence of an event of interest.
        scoring : array-like
            Continuous scores generated by the model used to determine predictions.
        sorted_scoring : numpy.ndarray
            Prediction scores sorted in ascending order, which are used to calculate thresholds.

        Methods:
        --------
        f1_with_thres(index):
            Calculates the F1 score for a specific threshold index.

        go():
            Calculates the F1 scores for all thresholds in parallel.

        __call__(x):
            Allows the class instance to be called as a function to calculate the F1 score
            for a specific threshold index.
    """
    def __init__(self,gt_labels,scoring):
        """
            Initializes the pointwise_best_f1 class.

            Parameters:
            -----------
            gt_labels : array-like
                Ground truth labels indicating the presence (1) or absence (0) of an event.
            scoring : array-like
                Continuous scores generated by the model to determine predictions.
        """
        self.gt_labels = gt_labels
        self.scoring = scoring
        self.sorted_scoring = np.sort(np.array(scoring))

    def f1_with_thres(self,index):
        """
            Calculates the F1 score for a specific threshold index.

            Parameters:
            -----------
            index : int
                Index in the sorted scoring list to be used to set the threshold.

            Returns:
            --------
            float
                The F1 score calculated for the corresponding threshold.
        """
        thres = self.sorted_scoring[index]
        pred_labels = self.scoring > thres
        f1 = f1_score(self.gt_labels, pred_labels)
        return f1

    def go(self):
        """
            Calculates the F1 scores for all thresholds in parallel.

            This method uses a pool of processes to efficiently compute the F1 scores for all
            possible thresholds.

            Returns:
            --------
            list
                A list of F1 scores for each threshold.
        """
        print('processing pointwise best f1')
        p = Pool()
        sc = p.map(self, range(len(self.scoring)))

        return sc

    def __call__(self, x):
        """
            Allows the class instance to be called as a function.

            This method is used to calculate the F1 score for a specific threshold index.

            Parameters:
            -----------
            x : int
                Index in the sorted scoring list to be used to set the threshold.

            Returns:
            --------
            float
                The F1 score calculated for the corresponding threshold.
        """
        return self.f1_with_thres(x)


class early_best_f1():
    """
        Evaluator to calculate the best early detection F1 score based on different scoring thresholds and specified delays.

        This class allows for the evaluation of a model's early detection performance by calculating the F1 score
        at various thresholds derived from scoring metrics, taking into account different time delays. It is useful
        for assessing the efficacy of detection algorithms in scenarios where timely predictions are critical.

        Attributes:
        -----------
        gt_labels : array-like
            Ground truth labels (0 or 1) indicating the presence or absence of an event of interest.
        scoring : array-like
            Continuous scores generated by the model used to determine predictions.
        sorted_scoring : numpy.ndarray
            Prediction scores sorted in ascending order, which are used to calculate thresholds.
        delay : list
            List of delays to assess the F1 score across different time lags.

        Methods:
        --------
        early_f1(index):
            Computes the F1 score for a specific threshold index, considering early detection with a specified delay.

        go():
            Executes the evaluation of the best early detection F1 score using multiprocessing.

        __call__(x):
            Allows the class instance to be called as a function to calculate the F1 score for a specific threshold index.
    """
    def __init__(self, gt_labels, scoring,delay):
        """
            Initializes the early_best_f1 class.

            Parameters:
            -----------
            gt_labels : array-like
                Ground truth labels indicating the presence (1) or absence (0) of an event.
            scoring : array-like
                Continuous scores generated by the model to determine predictions.
            delay : list
                List of delays for early detection evaluation.
        """
        self.gt_labels = gt_labels
        self.scoring = scoring
        self.sorted_scoring = np.sort(np.array(scoring))
        self.delay = delay

    # Multi pool
    def early_f1(self,idx):
        """
            Computes the F1 score for a specific threshold index, considering early detection with a specified delay.

            Parameters:
            -----------
            idx : int
                Index in the sorted scoring list to be used to set the threshold.

            Returns:
            --------
            float
                The F1 score calculated for the corresponding threshold, evaluated against the ground truth labels.
        """
        threshold = self.sorted_scoring[idx]
        result = np.array(self.scoring) > threshold
        score = label_evaluation(self.gt_labels, result.tolist(), self.delay)
        return score

    def go(self):
        """
            Executes the evaluation of the best early detection F1 score using multiprocessing.

            This method prints the delay values being processed and utilizes a Pool to compute the scores
            for each index in the sorted scoring array.

            Returns:
            --------
            list
                A list of F1 scores corresponding to each threshold evaluated.
        """
        print('processing early detection best f1 with delay ',str(self.delay))
        p = Pool()
        sc = p.map(self, range(len(self.scoring)))
        return sc

    def __call__(self, x):
        """
            Allows the class instance to be called as a function.

            This method is used to calculate the F1 score for a specific threshold index.

            Parameters:
            -----------
            x : int
                Index in the sorted scoring list to be used to set the threshold.

            Returns:
            --------
            float
                The F1 score calculated for the corresponding threshold.
        """
        return self.early_f1(x)


# consider delay threshold and missing segments
def get_range_proba(predict, label, delay=7):
    """
        Adjusts prediction probabilities based on the ground truth labels and specified delay for anomalies.

        This function analyzes the predicted values for anomalies and modifies them based on the occurrence
        of anomalies in the ground truth labels. If an anomaly is detected, it sets a range of predictions to 1
        (indicating an anomaly) if any predicted value within a specified delay period is also an anomaly.

        Parameters:
        -----------
        predict : array-like
            The predicted probabilities or binary classifications from the model (0 or 1).
        label : array-like
            The ground truth labels indicating the presence (1) or absence (0) of anomalies.
        delay : int, optional
            The number of time steps to look ahead when determining if a prediction should be marked as an anomaly.
            Defaults to 7.

        Returns:
        --------
        numpy.ndarray
            An array of the adjusted predictions, where ranges of predictions are set to 1 if an anomaly is detected
            within the specified delay period.
    """
    splits = np.where(label[1:] != label[:-1])[0] + 1
    is_anomaly = label[0] == 1
    new_predict = np.array(predict)
    pos = 0

    for sp in splits:
        if is_anomaly:
            if 1 in predict[pos:min(pos + delay + 1, sp)]:
                new_predict[pos: sp] = 1
            else:
                new_predict[pos: sp] = 0
        is_anomaly = not is_anomaly
        pos = sp
    sp = len(label)

    if is_anomaly:  # anomaly in the end
        if 1 in predict[pos: min(pos + delay + 1, sp)]:
            new_predict[pos: sp] = 1
        else:
            new_predict[pos: sp] = 0

    return new_predict


# set missing = 0
def reconstruct_label(timestamp, label):
    """
        Reconstructs a label array based on the given timestamps.

        This function takes a list of timestamps and corresponding labels, sorts the timestamps,
        and reconstructs the label array to match the intervals of the sorted timestamps.
        The reconstruction involves creating a new label array where each unique timestamp interval
        corresponds to the provided labels.

        Parameters:
        -----------
        timestamp : array-like
            The original timestamps associated with each label, which can be of any numerical type.
        label : array-like
            The labels corresponding to the original timestamps, indicating the presence (1) or absence (0)
            of a particular event.

        Returns:
        --------
        numpy.ndarray
            A reconstructed label array where the labels are aligned to the intervals of the sorted timestamps.
            The output has a length equal to the number of unique intervals between the timestamps.
    """
    timestamp = np.asarray(timestamp, np.int64)
    index = np.argsort(timestamp)

    timestamp_sorted = np.asarray(timestamp[index])
    interval = np.min(np.diff(timestamp_sorted))

    label = np.asarray(label, np.int64)
    label = np.asarray(label[index])

    idx = (timestamp_sorted - timestamp_sorted[0]) // interval

    new_label = np.zeros(shape=((timestamp_sorted[-1] - timestamp_sorted[0]) // interval + 1,), dtype=int)
    new_label[idx] = label

    return new_label


def label_evaluation(truth_list, result_list, delay=7):
    """
        Evaluates the performance of predicted labels against ground truth labels.

        This function reconstructs the labels from the given truth and prediction lists,
        applies a delay to the predicted labels to account for early detection evaluation,
        and computes the F1 score based on the reconstructed labels.

        Parameters:
        -----------
        truth_list : array-like
            A list of ground truth labels (0 or 1) indicating the presence or absence of an event.
        result_list : array-like
            A list of predicted labels (0 or 1) generated by the model for comparison against the ground truth.
        delay : int, optional
            The number of time steps to consider for early detection evaluation. Default is 7.

        Returns:
        --------
        float
            The F1 score computed from the ground truth and predicted labels, reflecting the accuracy of the predictions.
    """
    truth_df = {'timestamp': range(len(truth_list)), 'label': truth_list}
    result_df = {'timestamp': range(len(result_list)), 'predict': result_list}

    y_true_list = []
    y_pred_list = []
    # Adapted from: https://arxiv.org/pdf/1906.03821.pdf
    truth = truth_df
    y_true = reconstruct_label(truth["timestamp"], truth["label"])
    result = result_df
    y_pred = reconstruct_label(result["timestamp"], result["predict"])
    y_pred = get_range_proba(y_pred, y_true, delay)
    y_true_list.append(y_true)
    y_pred_list.append(y_pred)

    # run f1score
    fscore = f1_score(np.concatenate(y_true_list), np.concatenate(y_pred_list))
    return fscore

